### ISSUE TITLE
Example clarification

### ISSUE THREAD

**Issue by squaretone** [yibn2008/find-process#1]
In the README.md there is the following [example](https://github.com/yibn2008/find-process#example) to find process which is listening port 80:
```javascript
const find = require('find-process');

find('port', 80)
  .then(function (list) {
    if (!list.length) {
      console.log('port 80 is free now');
    } else {
      console.log('%s is listening port 80', list[0].name);
    }
  })
```
The `console.log('port 80 is free now');` line will never be called because, in [lib/find_pid.js line 34](https://github.com/yibn2008/find-process/blob/master/lib/find_pid.js#L34), Array.find is used to search for the id. If no process is using that port, then Array.find will return `undefined` as the value of `columns` so [line 41](https://github.com/yibn2008/find-process/blob/master/lib/find_pid.js#L41) will _always_ reject the Promise.

Is the intent of the code to resolve the Promise with an empty array (as seems to be the intent of the example) or should the example be changed to something like the following:

```javascript
const find = require('find-process');

find('port', 80)
  .then(function (list) {
      console.log('%s is listening port 80', list[0].name);
  })
  .catch(
    function(reason) {
      console.log('port 80 is free now');
    }
  )
```

**Comment by yibn2008** [comment]
I think it's a bug. If no error threw, the list param should always be Array. I'll fix it later.

Thanks :-)
