### ISSUE TITLE
wmi commandline utility start new process running for every few seconds and makes system hang by using more cpu usage

### ISSUE THREAD

**Issue by maheshatti** [yibn2008/find-process#10]
Hi, i am running find-process for every few seconds using set interval,because of this wmic commandline utility starts its process for every few seconds  and makes system hang by consuming more cpu usage.
Any help on this would be appreciated,Thank You

**Comment by yibn2008** [comment]
Since find-process use command line to get process info, this problem seems inevitable. What scenes will be called so frequently?

**Comment by maheshatti** [comment]
WMI Command line is called frequently

**Comment by maheshatti** [comment]
@yibn2008 WMI command line utility is running frequently.

**Comment by yibn2008** [comment]
@maheshatti find-process doesn't suit for frequently invoking scenes, please use another solution
