### ISSUE TITLE
Getting output (stdout) from a process

### ISSUE THREAD

**Issue by mightytyphoon** [yibn2008/find-process#11]
Hi guys,

Is it possible to get the output of a process when you know its pid ? I'm blocking on that, I have 2 subchildren of a spawn and I can get the output from the spawn but not from the 2 subchildren. I succeded to get their pid and I can kill them but it seems impossible to get their output.

Regards.

**Comment by yibn2008** [comment]
it's impossible ..., unless you spawn a child process and get it's stdout

**Comment by mightytyphoon** [comment]
@yibn2008 Ok, it's kind of annoying that there is no way in node to handle subchildren's output. Thank you for the answer.
