### ISSUE TITLE
Avoid prompting for password

### ISSUE THREAD

**Issue by mzedeler** [yibn2008/find-process#16]
This tool is an obvious attack vector since it prompts for password if running on linux (and searching for a process by port number).

There should be a flag to switch off this behavior, so the tool just fails if a password is required.

**Comment by mzedeler** [comment]
I've looked into this a little further and this tool shouldn't run sudo. It is the responsibility of the user. I propose to remove it her:

https://github.com/yibn2008/find-process/blob/master/lib/find_pid.js#L70

**Comment by yibn2008** [comment]
try v1.4.0
