### ISSUE TITLE
Build error A 'declare' modifier is required

### ISSUE THREAD

**Issue by FejZa** [yibn2008/find-process#17]
Hi,

when building my code using `tsc mycode.ts --lib es6` I keep getting this error. The output JavaScript works fine though.

`node_modules/find-process/index.d.ts:1:1 - error TS1046: A 'declare' modifier is required for a top level declaration in a .d.ts file.`

```function find(type: "name" | "pid" | "port", value: string | number | RegExp, strict?: boolean): Promise<{```

**Comment by yibn2008** [comment]
@FejZa fixed: find-process@1.2.1

**Comment by FejZa** [comment]
Thanks a lot!
