### ISSUE TITLE
using exe in name of process returns no results

### ISSUE THREAD

**Issue by tzarebczan** [yibn2008/find-process#18]
Process list:
 [ { pid: '51460',
      ppid: '22520',
      uid: null,
      gid: null,
      name: 'lbrynet.exe',
      cmd: 'lbrynet  start' },
    { pid: '39964',
      ppid: '51460',
      uid: null,
      gid: null,
      name: 'lbrynet.exe',
      cmd: 'lbrynet  start' } ]

Call:
  const processListArgs = 'lbrynet.exe';
  const processList = await findProcess('name', processListArgs);

This fails to return the process with or without strict mode on. 

We'll use 'lbrynet start' for now, but it requires us to pass as 'lbrynet  start' - with an extra space because that's how WMIC returns it.

**Comment by yibn2008** [comment]
try about latest version, may have solved your problem
