### ISSUE TITLE
Process name shows incorrect

### ISSUE THREAD

**Issue by fpsqdb** [yibn2008/find-process#19]
**Platform:** Mac OS
**Process:** Visual Studio Code
**Result:**
```
{
    name: 'Visual',
    cmd: '/Application/Visual Studio Code.app/Contents/MacOS/Electron'
}
```
The correct VSCode process name in `Activity Monitor` is `Code`.

**Comment by tengfei-blacksketch** [comment]
Any update?

**Comment by yibn2008** [comment]
@tengfei-blacksketch try `1.2.2`, just released and solved this problem.
