### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by drywolf** [yibn2008/find-process#2]
The example code always ends with the error `stdout maxBuffer exceeded`

    find('pid', 123)
      .then(function (list) {
        console.log(list);
      }, function (err) {
        console.log(err.message);
      });

Tested on node v6.5.0

**Comment by yibn2008** [comment]
please execute the `netstat` command according to your os type, the full `netstat` command is here: https://github.com/yibn2008/find-process/blob/master/example/netstat.md, the paste result in the comments.

**Comment by JR-Utily** [comment]
I have the same issue, with port option, on windows

here is the script I run
```
const find = require('find-process');

 find('port', 4444)
   .then(function (list) {
       console.log(list);
         }, 
     function (err) {
             console.log(err.stack || err);
       })

```
and the result of my netstat

```
$ netstat -ano | grep 4444
  TCP    0.0.0.0:4444           0.0.0.0:0              LISTENING       10284
  TCP    [::]:4444              [::]:0                 LISTENING       10284


```

**Comment by JR-Utily** [comment]
I've detect that this is the call of  `WMIC path [...] ` that raise an error, here is the log of it (with a grep on 4444)
[wmic.log.txt](https://github.com/yibn2008/find-process/files/1022773/wmic.log.txt)

**Comment by yibn2008** [comment]
@JR-Utily Thanks for these test cases, I'll take some spare time to fix it, maybe this weekend. Also if you have any solution, it will be awesome to sending me a PR

**Comment by JR-Utily** [comment]
in my case, WMIC command answer is very large (as in any running server, I guess)
```
WMIC path win32_process get Name,Processid,ParentProcessId,Commandline  | wc -m
701583

```
and I've seen there is a default max buffer for child process set to `200*1024 = 204800` that can be overridden.
So setting it to `2000*1024` solved my problem. 

```
find-process/lib/find_process.js:82
cp.exec(cmd, {maxBuffer:2000*1024}, function (err, stdout, stderr) { ...

```
An official fix is welcomed so the rest of my team can have it too :)

**Comment by jsmorris** [comment]
I am running into this issue and the fix suggested by @JR-Utily worked for me as well.

**Comment by yibn2008** [comment]
the bug should be fixed, and now you can use find-process as a CLI tool
