### ISSUE TITLE
Silent error on find PID if `ps` does not exist on *nix platform

### ISSUE THREAD

**Issue by brandonbird** [yibn2008/find-process#21]
This is an edge case but if you have a slim *nix install that doesn't include `ps`, trying to find a process by PID results in just an empty array instead of an error (https://github.com/yibn2008/find-process/blob/master/lib/find_process.js#L35-L36).

Perhaps the existence of the necessary utilities by platform should be checked for in a pre-install script.

**Comment by yibn2008** [comment]
I think you should do a pre-check to make sure your system has `ps` command before you call find-process. find-process assume your system is normal and already has these necessary dependencies.
