### ISSUE TITLE
Cannot find PID on Windows 10 when process with very long command line running

### ISSUE THREAD

**Issue by fberthelon** [yibn2008/find-process#29]
Hi,

I'm testing your library (v1.4.1) to retrieve process path from PID.
It is working perfectly except when I'm running a process with very long command line arguments.

I noticed that when I'm running IntelliJ IDE (which has nothing to do with my application using find-process) my application is not able to find any PID.

It looks like WMIC output is not consistent when command line column is very big (in my case more than 8000 characters for intelliJ only). And the parsing function is not able to retrieve PIDs.

Thanks again for what you have done with this library!

**Comment by fberthelon** [comment]
Hi,
After more investigation I found that WMIC command add a new line character (\n) at the end of command line header when it is tool long for one of the process listed. The behavior does not happen all the time.

When intelliJ is running I sure to get this error at least one time on 10 requests which is not the case when intelliJ is not running (no error after more than 100 requests).

**Comment by yibn2008** [comment]
already fixed in the latest release.
