### ISSUE TITLE
Command name with whitespaces is truncated on Mac OS

### ISSUE THREAD

**Issue by arcusfelis** [yibn2008/find-process#32]
`ps ax -ww -o pid,ppid,uid,comm,args` should not be used, but `ps ax -ww -o pid,comm`, if you want to parse `bin` field correctly.

Otherwise, there is no way to split arguments from command.

Consider calling ps command twice, if you really need command arguments. If you don't need arguments, `comm` should be enough.

**Comment by yibn2008** [comment]
already fixed on OSX system
