### ISSUE TITLE
Provide port details (if binded) for find process PID

### ISSUE THREAD

**Issue by ghost** [yibn2008/find-process#33]
Hi,
regarding to the subject that was also discussed in #28 ,
any workarounds / future PR for that ?

The most naive solution might be to create the following flow:

the caller runs findProcess('pid',<pid>)
in find_process.js before returning the now found process details,
Check if finders[find] returned response with process details,
Then for the fetched process, run the commands logic implemented in find pid by port but instead of matching the port in
if (matches && matches[1] === String(port))
match the pid
then return the data received by concat both of the results

**Comment by mcorrigan** [comment]
+1 This would be helpful
