### ISSUE TITLE
Does not work in container

### ISSUE THREAD

**Issue by brcnblc** [yibn2008/find-process#38]
It does not work properly in container image.

Container: node:12-alpine

**Comment by jayadrathamondal** [comment]
# gliderlabs/docker-alpine/issues/173#issuecomment-218620191

**Comment by jayadrathamondal** [comment]
https://github.com/gliderlabs/docker-alpine/issues/173

**Comment by jayadrathamondal** [comment]
gliderlabs/docker-alpine/#173

**Comment by jayadrathamondal** [comment]
#gliderlabs/docker-alpine#173

**Comment by jayadrathamondal** [comment]
gliderlabs/docker-alpine#173

**Comment by yibn2008** [comment]
find-process work require system commands, see https://github.com/yibn2008/find-process/tree/master/example to make sure your system/container supports these commands
