### ISSUE TITLE
Check the process owner or any mapping between user and process before killing process in Node JS

### ISSUE THREAD

**Issue by vaibhavrmore1** [yibn2008/find-process#49]
If you use "find" to get the processes of some name and the system is multiuser, it will return processes from all users. Hence before killing any process it's good to check if the process is owned by current used by mapping any means like owner or userid.

For eg.
1. Start some known process.
2. Kill that process. (It can kill the same process from other users)

The below code snippet can be added for any node console app.

               const find = require('find-process');

                find('name', 'Teams', true).then(function (list) {
                var i;
                for (i = 0; i < list.length; i++) {                   
                    process.kill(list[i].pid);
                  }
                });
                
  Also, I see that from the returned process, uid and gid in Windows are undefined.

**Comment by yibn2008** [comment]
Currently, I have no plan on the user filtering feature, but if you really want this in the find-process, a pull request will be welcome.
