### ISSUE TITLE
[QUESTION]为什么不用tasklist来获取

### ISSUE THREAD

**Issue by xmsz** [yibn2008/find-process#63]
背景
- windows
- 获取指定名称的进程
- 我用findProcess需要5s左右
- 用tasklist只需要500ms

问题
- 为什么不用tasklist

**Comment by zzpbuaa** [comment]
I have the same issue. It will take around 6s on Windows when I use this in Electron. But when I debug the JS script directly in VS Code, it returned very soon.

**Comment by yibn2008** [comment]
Sorry I don't have the environment to reproduce this issue.
