### ISSUE TITLE
Allow search by multiple options of one type in one call

### ISSUE THREAD

**Issue by mcorrigan** [yibn2008/find-process#65]
It would be great to be able to pass an array of possible values to match and get all the results back at once. I realize that it is possible to  do them one at a time, but this seems like it could be more performant if the library handles it. 

for instance:
`find('pid', [1234. 2345]); `

This could return 0-2 results. 

For ports, you would likely need to include this #33 so that we can tell which ones matched.

**Comment by yibn2008** [comment]
Sorry I don't have plan to support this feature so far as it was designed to find single process. 

I will merge your PR if it's well designed~
