### ISSUE TITLE
Can't find child processes by name on win32

### ISSUE THREAD

**Issue by 464bb26bac556e85b6fd6b524347b103** [yibn2008/find-process#9]
It looks like currently if you use child_process.spawn on win32 with detached:false, find-process is unable to find the process by name when search from within the same parent process that spawned the child.

I didn't test to see if this is a broader issue but the specified case should reproduce

**Comment by yibn2008** [comment]
you can use https://github.com/yibn2008/find-process/blob/master/example/process.md to test if the process exists

**Comment by hanjianqiao** [comment]
I have save problem, and I think find_process by `name` always search in `cmd` 
```javascript
find('name', 'svchost')
  .then(function (list) {
    console.log(list);
  }, function (err) {
    console.log(err.stack || err);
  })
```
![image](https://user-images.githubusercontent.com/7146341/49418586-e94fc980-f7bd-11e8-82dc-aaeab4fb8d1a.png)
but not these
![image](https://user-images.githubusercontent.com/7146341/49418598-fcfb3000-f7bd-11e8-9649-8dfc2e381a31.png)

**Comment by yibn2008** [comment]
fixed, try latest version
